### ISSUE TITLE
Allow parameters in baseUrl

### ISSUE THREAD

**Issue by bakura10** [guzzle/guzzle-services#102]
Hi,

I can see from the serializer that the URI template is resolved only for the path part: https://github.com/guzzle/guzzle-services/blob/guzzle6/src/Serializer.php#L148

However, it would be very nice if this could be made AFTER merging with the baseUrl, so we could have a service spec like that:

```php
return [
   'baseUrl' => 'https://{prefix}.test.com'
];
```

Thanks!

**Comment by Konafets** [comment]
Where does the `prefix` comes from?

**Comment by bakura10** [comment]
Hi,

Actually, I don't remember why I was asking that tbh :p. I think I was able to workaround by changing the base url programmatically. I'd say we could close. If I come around the use case again in the future I'll re-open with more details.
