### ISSUE TITLE
How to create dynamic XML from array

### ISSUE THREAD

**Issue by fillup** [guzzle/guzzle-services#104]
I understand how to use the xml location for defining specific XML structures by defining a parameter with properties which have properties, etc. 

But is there a way to just provide an array and have it serialized to XML automatically without needing to know the full structure before hand?

For example, say I want to send the following as the body:

``` xml
<?xml version="1.0"?>
<People>
    <Person>
        <name>
            <given>Phillip</given>
            <surname>Shipley</surname>
        </name>
        <email>phillip@example.com</email>
        <address>
            <street1>123 Somewhere</street1>
            <street2>Suite 123</street2>
            <city>Anytown</city>
            <state>CA</state>
            <country>USA</country>
        </address>
    </Person>
</People>
```

I would really like to just call the operation like:

``` php
$person = $client->create([
    'person' => [
        'name' => [
            'given' => 'Phillip',
            'surname' => 'Shipley',
        ],
        'email' => 'phillip@example.com',
        'address' => [
            'street1' => '123 Somewhere',
            'street2' => 'Suite 123',
            'city' => 'Anytown',
            'state' => 'CA',
            'country' => 'USA',
        ],
    ],
]);
```

And I would like to define the operation something like:

``` php
'Create' => [
    'httpMethod' => 'POST',
    'uri' => '/{ApiVersion}/people',
    'data' => [
        'xmlRoot' => [
            'name' => 'people',
        ],
    ],
    'parameters' => [
        'ApiVersion' => [
            'required' => true,
            'type'     => 'string',
            'location' => 'uri',
        ],
        'Content-type' => [
            'required' => true,
            'type' => 'string',
            'location' => 'header',
            'default' => 'application/xml',
        ],
        'person' => [
            'required' => true,
            'type' => 'object',
            'location' => 'xml',
        ],
    ],
],
```

I just cant figure out how to define the operation in my description file. I've tried using additionalParameters but with no luck.

Can you provide an example of how to do what I'm trying to do or let me know if it isn't possible?

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
