### ISSUE TITLE
Please create version tag for current master branch

### ISSUE THREAD

**Issue by fillup** [guzzle/guzzle-services#110]
I've developed an sdk that uses this library but it depends on some fixes that are in master branch but are not part of the latest release tag `0.5.0`. So I have to depend on `dev-master` in my `composer.json` but doing so causes problems for users of my sdk because it violates their minimum stability setting. Can you create a tag for current master branch so I can depend on a version rather than `dev-master`?

**Comment by fillup** [comment]
@jeremeamia @mtdowling Any chance you can push a quick tag?

**Comment by Konafets** [comment]
1.0.0 was released yesterday. Please test and reopen this issue if your problem still exists.

**Comment by forevermatt** [comment]
Excellent. This is very helpful. Thanks, @Konafets 😄
