### ISSUE TITLE
Introduce a new Configuration object

### ISSUE THREAD

**Issue by Konafets** [guzzle/guzzle-services#114]
The Configuration object holds the config in an internal array. It should fullfil the following requirements:
- expose methods to access the configuration
- validates the configuration
- exposes `has()` method to check if a certain key set. Then we can declutter the code from `isset($config[*])` Methods.

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
