### ISSUE TITLE
AbstractClient' not found

### ISSUE THREAD

**Issue by 2ndGAB** [guzzle/guzzle-services#117]
Hello,
I've installed [guzzle-services](https://github.com/guzzle/guzzle-services/tree/guzzle6), [guzzle-command](https://github.com/guzzle/command/tree/guzzle6) and [guzzle 6](https://github.com/guzzle/guzzle) and on execution, I get the following error.

    Error: Class 'GuzzleHttp\Command\AbstractClient' not found
    File /var/www/2ndGuide/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php
    Line: 17

Any idea?

**Comment by 2ndGAB** [comment]
Sorry I think my problem comes from repository clone

**Comment by Konafets** [comment]
Please stay within #116  to solve the problem.

**Comment by 2ndGAB** [comment]
I fighted a bit with dependencies to be able to install guzzle, guzzle-services and guzzle-command which are depending on other module.
I finally got everything.
Unfortunately, it's not so easy to migrate to guzzle 6 as Event class desappeared so that suppose to modify the topmost module using guzzlehttp.
So, I have to see that with the developper.... :-/
