### ISSUE TITLE
Tag pre 1.0.0 release

### ISSUE THREAD

**Issue by kachar** [guzzle/guzzle-services#121]
Can you please create a new tag for the last commit with support for php < 5.5

We can't update composer on that platform and we have to switch from `dev-master` to specific commit `d8465d5f0a282192db4f0438ca6f2801fdd8b000`

The previous release before `1.0.0` is `0.5.0` created on Dec 23, 2014

**Comment by Konafets** [comment]
Does `composer require guzzlehttp/guzzle-services:0.5.*` not work for you?

**Comment by kachar** [comment]
It will load the version from 2014, not a recent version before the migration to guzzle 6

**Comment by Konafets** [comment]
Every version has its own tag. All versions prior 1.0.0 uses Guzzle 5 or lower.

**Comment by kachar** [comment]
In the tags page I see only `0.5.0` and `1.0.0`
https://github.com/guzzle/guzzle-services/tags

If you create a tag `0.9.0` or similar from `d8465d5f0a282192db4f0438ca6f2801fdd8b000` it will be a prior php 5.5 and we can point composer to that one with `0.9.*`

**Comment by kachar** [comment]
That happens because there is no regular release on the repo for the last 2 years.

**Comment by Konafets** [comment]
As you mentioned correctly there was no release between 0.5 and 1.0.0 and this is the reason why there is no need for an extra tag. Version 0.5 uses Guzzle 5 and requires PHP 5.4+. 

Here is a [link](https://github.com/guzzle/guzzle-services/tree/5402867628d266748db88f05c90ede54fd1d884c) to the code when it was taggged as 0.5. Have a look in the [composer.json](https://github.com/guzzle/guzzle-services/blob/5402867628d266748db88f05c90ede54fd1d884c/composer.json#L14) which defines PHP5.4 as a requirement.

**Comment by kachar** [comment]
Thanks a lot! I think we can close the thread now
