### ISSUE TITLE
Header's keys are not the keys from the array

### ISSUE THREAD

**Issue by mims92** [guzzle/guzzle-services#122]
Following the documentation,'

> Headers that are of type object will be added as multiple headers to a request using the key of the input array as the header key  (http://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#header-location).

But it's not the case!

```
"getChocolate": {
      "httpMethod": "GET",
      "uri": "api/getChocolate/{id}",
      "parameters": {
       "id": {
          "required": true,
          "location": "uri",
          "type": "integer"
        },
        "header": {
          "required": false,
          "location": "header",
          "type": "object"
        }
      }
}
```

So if I pass `['myCustomHeader' => '1']` to the `header` parameter, I would assume having in the request header:
`myCustomHeader: 1`.
Actually, I have
`header: 1`.

Is this a bug?
Using Guzzle6

**Comment by Konafets** [comment]
It looks like this has gone long time ago. Can't even find this described behavior in the origin code of Guzzle3 anymore. My first guess is that the docs are outdated.

**Comment by MI-LA01** [comment]
I don't know if this can help, but i confirm we facing the same issue right now, As a workaround, you can define the header name as the key for the array like this 

```
'X-Access-Token' => [
     'required' => true,
     'location'  => 'header',
     'type'        => 'string'
]
```

**Comment by mims92** [comment]
I don't think it's a workaround. I think it's the correct way of doing this and the doc is outdated as Konafets mentioned.

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
