### ISSUE TITLE
Question: How to run filter on response object?

### ISSUE THREAD

**Issue by tmikaeld** [guzzle/guzzle-services#133]
I've tried this:

````php
           'models'      => [
                'json'       => [
                    'type'                 => 'object',
                    'additionalProperties' => [ 
                        'location' => 'json',
                        'filters'  => [ 'BcClient::objectToArray' ]
                    ]
                ]
            ]
````

But the response never get processed, the filter function does work on the response without filters.

**Comment by danizord** [comment]
@tmikaeld I'm having the same issue here. Have you managed to achive this?

**Comment by tmikaeld** [comment]
@danizord Unfortunately not, I'm stick stuck on it

**Comment by Konafets** [comment]
`models` has no `filters`. http://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#service-description-schema

**Comment by Konafets** [comment]
I thought it was done because you closed it. Let me have look what happens there.

**Comment by danizord** [comment]
@Konafets According to the schema you linked, the properties of `models` is a `$ref` of `parameters`, which does contain `filters`.

**Comment by Konafets** [comment]
Yes, that I was figure out too and edited my comment ;-)

**Comment by tmikaeld** [comment]
@Konafets I saw the docs too, but figured it was only for single values.

And i found another project that used this.

I closed it because i figured i did something wrong and didn't have time to fiddle with it.

**Comment by tmikaeld** [comment]
I'm still curious for a solution though, I'd rather do it properly.

**Comment by danizord** [comment]
Hey @tmikaeld and @Konafets, I've sent a PR to fix this: https://github.com/guzzle/guzzle-services/pull/138

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
