### ISSUE TITLE
Posting array as JSON body

### ISSUE THREAD

**Issue by aequasi** [guzzle/guzzle-services#142]
I'm trying to post the following JSON, but im not sure how to set up my operation...

```json
[
    {"id": 123978591827912, "position": 1},
    {"id": 1233142151622314, "position": 2},
    {"id": 123972727245623, "position": 3}
]
```

**Comment by bangpound** [comment]
Did you solve this problem @aequasi ? I'm encountering the same thing.

**Comment by aequasi** [comment]
Nope, i just wrote my own function to handle it.

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
