### ISSUE TITLE
Default values ignored in 1.1

### ISSUE THREAD

**Issue by Rarst** [guzzle/guzzle-services#146]
If I update to 1.1.1 my operations start to fail, since `default` values for parameters are ignored and omitted.

Like [here](https://github.com/Rarst/wporg-client/blob/d4f2def6a80a86a428d96fd323c327c308894109/php/WporgService.php#L129-L136) `version` becomes missing in URL and `action` becomes missing from POST, unless explicitly passed to command.

**Comment by selfcatering** [comment]
I can confirm same, all defaults are ignored.

**Comment by delamart** [comment]
I think my issue #145 might be related.

**Comment by selfcatering** [comment]
Failing test https://github.com/selfcatering/guzzle-services/commit/5987ac6ca2bee2f5770a6428a4cca3dd6b8a6738
