### ISSUE TITLE
Breaking change for object

### ISSUE THREAD

**Issue by bakura10** [guzzle/guzzle-services#148]
Hi,

I didn't have time to check yet, but we had a user of our library ZfrShopify having a breaking change in last version of Guzzle-Services (downgrading to 1.1.0 fixed the issue).

We have a descriptor that looks like this:

```php
        'GetMetafields' => [
            'httpMethod'       => 'GET',
            'uri'              => 'admin/metafields.json',
            'parameters'       => [
                'metafield' => [
                    'description' => 'Filter metafields by resource type and ID (accepts sub-fields "owner_id" and "owner_resource")',
                    'location'    => 'query',
                    'type'        => 'object',
                    'required'    => false
                ],
            ]
        ]
```

We called it this way:

```php
$shopifyClient->getMetafields([
  'metafield' => [
    'owner_id' => 123,
    'owner_resource' => 'product'
  ]
]);
```

This used to properly serializes those parameters as ?metafield[owner_id]=123&metafield[owner_resource]=product

In the last version, it apparently does not work and serialize it as ?metafield=123&metafield=product, so it's a rather big breaking change.

We'll try to have a look but if you already know the reason, it would be nice to revert!

**Comment by GrahamCampbell** [comment]
Did you get anywhere with debugging this?

**Comment by bakura10** [comment]
Hi Graham ! That’s a long time ago, I do not really remember. I unfortunately stopped backend development a few years ago.

**Comment by GrahamCampbell** [comment]
Ok, I'm going to close this out. :)
