### ISSUE TITLE
Weird behaviour without models

### ISSUE THREAD

**Issue by rdohms** [guzzle/guzzle-services#153]
In my meetup-api client I use the descriptions, but i don't use Models, since they would be too many to manage and unneeded.  With the previous version based on Guzzle 3 this would be fine and I would intercept the response and do my thing.

In this version it seems to return a completely empty `Result`, no HTTP code, nothing.
I was very confused and then I found this: https://github.com/guzzle/guzzle-services/blob/master/src/Deserializer.php#L92

```
            // Not sure if this should be empty or contains the response.
            // Decided to do it how it was in the old version for now.
            return new Result();
```

So I'm wondering if I took a wrong turn somewhere or maybe this is not what it should be doing? I did have a Custom Result Parser before, but i'm not sure which direction to follow this time.

**Comment by rodsouto** [comment]
I found this issue today, it's weird to return an empty result if we already have a valid response :/

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
