### ISSUE TITLE
Weird "equal equal not" operator

### ISSUE THREAD

**Issue by thedustin** [guzzle/guzzle-services#154]
I'm evaluating guzzle/guzzle-services at the moment for our team and scrolled a bit through the source code when I found a _weird_ operator I haven't seen yet: `==!`¹.
What does this operator do? After first experiments it looks like a weird `$var == !null`, but why do you write it this way? 

Thanks for your help and best regards.

¹ https://github.com/guzzle/guzzle-services/blob/master/src/GuzzleClient.php#L102

**Comment by Konafets** [comment]
To me it looks like it should be `!==`, but unintentionally it works anyway for the reason you describe. If can open an PR if you like.

**Comment by Konafets** [comment]
Fixed it myself :-)
