### ISSUE TITLE
Recommended test setup?

### ISSUE THREAD

**Issue by sandervanhooft** [guzzle/guzzle-services#155]
Hi,

I am writing an API client wrapper which I need to test. What is the recommended way to use guzzle services + mocking + history (request) tracking?

Does anyone have an example API client wrapper available?

I read through the Guzzle docs ([link](http://docs.guzzlephp.org/en/stable/testing.html)) and tried to find a solution in this repo('s issues), but it's not clear to me.

\- Sander

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
