### ISSUE TITLE
What am i doing wrong ?

### ISSUE THREAD

**Issue by marcoooo** [guzzle/guzzle-services#161]
Hi all. 
my services declares a method "list" as follow:

    "operations": {
        "list": {
        "httpMethod": "GET",
        "uri": "contacts",
        "summary": "List all contact",
        "responseModel": "ContactList",
        "parameters": {
          "card": {
            "type": "boolean",
            "location": "query",
            "required": false,
            "summary": "if true: Return only contacts with or without a loyalty card.",
             "filters": [
              "json_encode"
            ]
         }
       } 
    },

In my simpe test case: 

    $client = ContactApiClient::initClient('TOKENAUTH');
    var_dump($client->list(["card" => true]));

I got this error: 
    
    GuzzleHttp\Command\Exception\CommandException : 
    Validation errors: **[card] must be of type boolean** 
    in .../vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php:76

**Comment by tlorens** [comment]
If 'card' is mean to be a parameter, shouldn't `{card}` be included in the defined uri? 

` 'uri': "contacts/{card}"`

**Comment by adick** [comment]
Probably it's because of your json_encode filter, which casts your boolean true to a string "true".

@tlorens: no it shouldn't, because the specified location is `query`. This can be looked up in the [descriptions documentation](https://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#query-location).

**Comment by marcoooo** [comment]
> Probably it's because of the json_encode filter on your parameter, which casts your boolean true to a string "true".
> 
> @tlorens: no it shouldn't, because the specified location is `query`. This can be found in the [descriptions documentation](https://guzzle3.readthedocs.io/webservice-client/guzzle-service-descriptions.html#query-location)

Yes this was the reason, I finally found a workaround.
Thanks for your help anyway.
