### ISSUE TITLE
Tests Fail with guzzlehttp/psr7 >= 1.6.0

### ISSUE THREAD

**Issue by GuyPaddock** [guzzle/guzzle-services#166]
The 1.6.x release of `guzzlehttp/psr7` appears to have introduced additional checks and verifications that break tests for Guzzle Services. This persists even with version 1.6.1 of `guzzlehttp/psr7` which supposedly had rolled-back several type assertions to defer them until 2.0.0.

As a workaround, tests pass if `guzzlehttp/psr7` is downgraded to 1.5.2 with `composer require guzzlehttp/psr7:1.5.2`.

Test failures are attached.
[failures.log](https://github.com/guzzle/guzzle-services/files/3478430/failures.log)

This affects the `master` branch at 9e3abf20161cbf662d616cbb995f2811771759f7.

**Comment by GrahamCampbell** [comment]
Thanks for your work here. Fixed now. :)
