### ISSUE TITLE
Unify `extraData` in Descriptions

### ISSUE THREAD

**Issue by seiffert** [guzzle/guzzle-services#17]
I stumbled upon the fact that `Description`s use any information provided in the configuration array and add all keys it doesn't know to `Description::$extraData`. `Operation`s on the other hand neglect these additional keys unless they are provided in  `$config['data']`. 
With this issue I would like to ask you, @mtdowling, for your reasoning behind this and whether you think that a unified API would make sense here.
I'm implementing a custom response parsing mechanism which requires an additional attribute in each Operation. At the moment, I have to pass this attribute via `$config['data']`.

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
