### ISSUE TITLE
What branch is under active development?

### ISSUE THREAD

**Issue by GuyPaddock** [guzzle/guzzle-services#170]
It seems like this project is trying to use GIT Flow, with `master` being the branch where releases go after they're released, and `develop` being the branch where bleeding edge development ahead of a release is integrated. But... the default branch is `master` and a lot of recent PRs were merged to `master`. Consequently, the `master` and `develop` branches have diverged.

If this project is following GIT flow, then a maintainer should bring `develop` up-to-speed with the latest from `master`, create a release, and then make `develop` the default branch for future PRs.

**Comment by phareous** [comment]
looks like this project is abandoned now, no commits in two years, and a bunch of pending pull requests and issues which haven't been addressed

**Comment by GrahamCampbell** [comment]
master. the project is not abandoned. I am taking over here, with @Nyholm for an extra pair of eyes where required. :)
