### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by stof** [guzzle/guzzle-services#173]
This project (and its dependency https://github.com/guzzle/command) are currently requiring Guzzle 6, while Guzzle 7 is now the stable release. What is the plan for these packages ? Are they still maintained ? And if yes, will they support Guzzle 7 ?

**Comment by elijahchancey** [comment]
Please add support for Guzzle 7. I depend on several packages that depend on Guzzle Services. I'd like to upgrade to Guzzle 7 when possible.

**Comment by Konafets** [comment]
Hi, 

I am the last active maintainer as far as I know. Currently I have no project using this lib so I have no need nor testing environment for updating this to Guzzle 7. 

Everyone is invited to provide an PR :-)

**Comment by stof** [comment]
According to the changelog of guzzle 7, I think adding support for Guzzle 7 in https://github.com/guzzle/command and here should be quite easy actually. It might even be possible to support Guzzle 6 and 7 in a single version of these packages (BC breaks seems to be mostly for code extending the guzzle classes, and these 2 packages don't do it AFAICT).

**Comment by vduglued** [comment]
@stof are you thinking of contributing a PR? I'm working on something new and this package would be useful but, with the lack of activity, I wonder whether everyone's using something else as a simple generic REST client in PHP that I'm not aware of.

**Comment by bumbummen99** [comment]
Created a PR for guzzle/command (https://github.com/guzzle/command/pull/40) and this repository (https://github.com/guzzle/guzzle-services/pull/174)

**Comment by tlorens** [comment]
> @stof are you thinking of contributing a PR? I'm working on something new and this package would be useful but, with the lack of activity, I wonder whether everyone's using something else as a simple generic REST client in PHP that I'm not aware of.

I found this. 
https://github.com/8p/EightPointsGuzzleBundle

Looks like it's pretty close to this project.

**Comment by stof** [comment]
@tlorens not at all. EightPointsGuzzleBundle is about integrating Guzzle with Symfony to configure Guzzle clients. This guzzle-services package is about building SDKs on top of Guzzle.

**Comment by GrahamCampbell** [comment]
I am taking over here, with @Nyholm for an extra pair of eyes where required. :)
