### ISSUE TITLE
Not possible to install on PHP <=7.3

### ISSUE THREAD

**Issue by breenie** [guzzle/guzzle-services#178]
PHP 7.2

**Description**

The contributing guidelines stipulate a minimum version of 7.2, the minimum version in composer is >=7.3.

**How to reproduce**

Attempt a composer install using a PHP version == `7.2.x`.

**Possible Solution**
Partially revert https://github.com/guzzle/guzzle-services/commit/57759d6ffd2000e61d6e8a057f8e74c7c2a88409 

**Additional context**
The tip of guzzlehttp currently requires `^7.2.5 || ^8.0"`. I'm happy to make a PR but I wasn't sure if there was a reason for the edit. There doesn't seem to be an issue related to it.

**Comment by SoftCreatR** [comment]
I currently have the same problem.

**Comment by GrahamCampbell** [comment]
The next release will restore support for PHP 7.2.5 and higher.
