### ISSUE TITLE
Ran into composer issue because package does not auto update.

### ISSUE THREAD

**Issue by CodeByZach** [guzzle/guzzle-services#181]
<img width="1390" alt="Screen Shot 2021-08-23 at 7 43 19 PM" src="https://user-images.githubusercontent.com/20159826/130533359-2608043f-70ab-43e8-a163-22604c3889f5.png">

**Comment by GrahamCampbell** [comment]
What issue did you run into, in practice?

**Comment by CodeByZach** [comment]
> What issue did you run into, in practice?

In just one example below, references calls were being made to a now depreciated function in PSR7 which was causing the code to fail like so:
`Call to undefined function GuzzleHttp\\Psr7\\stream_for()`

Version 1.2.0:
https://github.com/guzzle/guzzle-services/blob/21e931a4784a132fa78ea7c37abf0e806b053c23/src/RequestLocation/JsonLocation.php#L50

Version 1.3.0 (latest)
https://github.com/guzzle/guzzle-services/blob/acd7ab1b83658ad7c1abd2a0871b825f65007202/src/RequestLocation/JsonLocation.php#L51

In all likelihood, my running of the manual update on Packagist saved people some time debugging.

**Comment by GrahamCampbell** [comment]
No, I already ran this after tagging v1.3.0. As you can see from your screenshot, any further manual runs won't have done anything since v1.3.0 was already there. Probably you just needed to run composer update locally.

**Comment by CodeByZach** [comment]
> No, I already ran this after tagging v1.3.0. As you can see from your screenshot, any further manual runs won't have done anything since v1.3.0 was already there. Probably you just needed to run composer update locally.

It most definitely was **not** already there. I took that screenshot after resolving the issue.

**Comment by GrahamCampbell** [comment]
Oh dear. I'm going to check in with Tobias about this.
