### ISSUE TITLE
Assigning data to the "root" of result?

### ISSUE THREAD

**Issue by Rarst** [guzzle/guzzle-services#64]
I am making a service for API that returns (sometimes) serialized PHP in response bodies.

This is model I have so far for them:

``` php
'serialized' => [
    'type'       => 'object',
    'properties' => [
        'body' => [
            'location' => 'body',
            'type'     => 'string',
            'filters'  => [ 'unserialize', 'get_object_vars' ],
        ],
    ],
```

But since I am not interested in anything else in response I would like to get rid of pointless "body" level in resulting array. `additionalProperties` approach doesn't seem to work here as it does with JSON or I can't figure out how to apply it.

**Comment by selfcatering** [comment]
Have you though about creating a custom deserializer that handles your scenario? You can implement `before` method for processing body when needed.

**Comment by Rarst** [comment]
Thank you for info, this is properly not worth the trouble for now and I will stick with handling this in calling methods.
