### ISSUE TITLE
Updating the description 

### ISSUE THREAD

**Issue by bakura10** [guzzle/guzzle-services#65]
Hi,

In Guzzle 3, there was a setDescription method. This is useful in some cases. I'm using this for my Stripe wrapper, so that depending on the version you want of Stripe, it loads a different descriptor.

What is the currently recommended way to do it? If there's no reason, I will do a PR to add it :).

Thanks!

**Comment by mtdowling** [comment]
This was omitted to reduce the mutability of the client. Allowing the description to change at runtime could require other collaborators to be aware of the change after the client is created (e.g., signing requests using a specific API version). This was an issue for us with the AWS SDK, so we decided to not allow the description to be mutable.

The recommended way to create clients with different versions is to inject the service description in the constructor of the client.

**Comment by bakura10** [comment]
I've ended up in making my Client not extended Guzzle Client, and creating the guzzle client each time I change the API version (https://github.com/zf-fr/zfr-stripe/blob/guzzle-5/src/Client/StripeClient.php#L316). I'm not sure if that's the best way (I'm not fond of having my StripeClient both a "httpClient" and "guzzleClient").

**Comment by mtdowling** [comment]
That sounds like the right approach.
