### ISSUE TITLE
Parameter type validation is too strict

### ISSUE THREAD

**Issue by thasmo** [guzzle/guzzle-services#7]
This is an operation I defined:
```
'users' => [
	'httpMethod'    => 'GET',
	'uri'           => 'users/{id}',
	'responseModel' => 'users',
	'parameters'    => [
		'id' => [
			'type'     => 'integer',
			'location' => 'uri',
			'required' => TRUE
		]
	]
]
```
When I'm calling the operation this way:
`$data = $client->users(['id' => '1574083']);`
this error comes up:
`Fatal error: Uncaught exception 'GuzzleHttp\Command\Exception\CommandException' with message 'Validation errors: [id] must be of type integer'`

Shouldn't an *integer-like* value be fine, although it's given as string?

**Comment by jwcobb** [comment]
@thasmo In October @mtdowling added the `number` and `numeric` types that should handle your issue.

@brunogaspar and @dao You can use `'format' => 'boolean-string'` which will convert booleans as you are describing.

**Comment by brunogaspar** [comment]
@jwcobb Thanks, i haven't played with this in a while, but will give that a try in a few days.

**Comment by mtdowling** [comment]
Closing now since the addition of number and numeric address this issue.
