### ISSUE TITLE
Returning mock responses

### ISSUE THREAD

**Issue by fgrosse** [guzzle/guzzle-services#70]
I try to write a test for a guzzle client which uses service descriptions.
The response is mocked like described in the [current guzzle documentation](http://guzzle.readthedocs.org/en/latest/testing.html)

``` php
use GuzzleHttp\Subscriber\Mock
...
// $client is a \GuzzleHttp\Command\Guzzle\GuzzleClient
$mock = new Mock([$fixturePath]);
$client->getHttpClient()->getEmitter()->attach($mock);
...
$result = $client->doStuff(); // calls the doStuff operation from the service description
```

This works fine and I could confirm that the mock is actually used.
However the `$result` is always an empty array even though the underlying transaction got the correct response.

Since I do only want to make test assertions on the request, this issue has not become a problem yet but I wonder if I am doing the tests correctly. Am I missing something here? Any help would be much appreciated

Also I wondered why I could not attach the response mock to the emitter of my client directly but had to use the underlying client implementation (using `getHttpClient()`).

**Comment by gimler** [comment]
It works for me. Can you post your Schema and the mock file please?

**Comment by fgrosse** [comment]
As you can see I created a minimal example to reproduce the issue.

**Comment by gimler** [comment]
You must define a responseModel.

**Comment by fgrosse** [comment]
Does that mean I always have to have a response model?
Until now I was using the guzzle 3 service descriptions which would just return an array if there is no response model :/

**Comment by gimler** [comment]
yes one workaround is that you can define a model for example array in the root file and than everytime use `responsModel: array`

**Comment by fgrosse** [comment]
mmh yeah that works but its kind of inconvenient especially if you come from guzzle 3.
What do you think about having a default response model which creates array responses. This could work with the response content-type to know how to interpret data.

Until something like that exists I will define and use the following model in all of my service definitions (have to copy it in all service definitions)

```yaml
operations:
    getFoo:
        ...
        responseModel: jsonResponse
        ...
...
models:
    jsonResponse:
        type: object
        additionalProperties:
            location: json
```

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
