### ISSUE TITLE
Allow shortened definition of properties in models

### ISSUE THREAD

**Issue by rfink** [guzzle/guzzle-services#71]
Instead of always:

"MyModel" => [
    "type" => "string"
]

To shorten it to:

"MyModel" => "string"

If it's a plain type and needs no other configuration.  Pull request coming shortly

**Comment by jeremeamia** [comment]
Sorry, this is really old. I recently took over this project, and am looking at issues and PRs now. Honestly, I'd rather not make this change, since it is not that beneficial, and it complicates the specification.
