### ISSUE TITLE
Allow to provide Post Body as an Array

### ISSUE THREAD

**Issue by quarkmarino** [guzzle/guzzle-services#77]
I've been learning Guzzle for the last week, and figured out a lot of stuff, but can`t make my service description to use the passed parameters array and take the parameters tagged for location 'body' and combine into an string, using postFiled for location, almost do it, but interpolates the & symbol, it would be nice to pass the body parameters just like the request body option array.

http://docs.guzzlephp.org/en/latest/clients.html#request-options

Thank you, i'm eager to know about the production ready tag.

**Comment by Konafets** [comment]
I will close this issue. If your problem still exist with latest versions of Guzzle and Guzzle Service, feel free to reopen it.
