### ISSUE TITLE
Regression of Issue #51 - XmlLocation response not handling multiple tags of the same name correctly

### ISSUE THREAD

**Issue by sprak3000** [guzzle/guzzle-services#82]
Issue #51 was closed as fixed, but it appears there is a regression that has cropped up around it. It is back to the same behavior seen before; the first node is off on its own instead of encapsulated as item 0 in the array for the tag.

It looks like a bit of code from my original fix got nerfed at some point; the `else if` out of the fix (`src/ResponseLocation/XmlLocation.php` method `xmlToArray`) got nerfed:

```
// A child element with this name exists so we're assuming
// that the node contains a list of elements
if (!is_array($result[$name])) {
  $result[$name] = [$result[$name]];
}
```

should be

```
// A child element with this name exists so we're assuming
// that the node contains a list of elements
if (!is_array($result[$name])) {
  $result[$name] = [$result[$name]];
}  else if (!isset($result[$name][0])) {
  // Convert the first child into the first element of a numerically indexed array
  $firstResult = $result[$name];
  $result[$name] = [];
  $result[$name][] = $firstResult;
}
```

I've tried patching this locally, and it clears up my issue. I'll get a PR going.

**Comment by fillup** [comment]
Was this ever merged back in? I'm using version 0.5 now and this issue is present. I can confirm that the fix above resolves the issue. @sprak3000 did you submit another PR?

**Comment by sprak3000** [comment]
@fillup I did submit a PR, and it was pulled into master (https://github.com/guzzle/guzzle-services/commit/dbd8aef6865cc39d000d8c15968f9792ae84829b).

They just haven't tagged an official release yet. Looks like they might be pulling more stuff in prior to a 0.6 tagged release.

Hope that helps.

**Comment by Konafets** [comment]
I will close this issue. If your problem still exist with latest versions of Guzzle and Guzzle Service, feel free to reopen it.
