### ISSUE TITLE
Mock Subscriber & Guzzle Services - empty array?

### ISSUE THREAD

**Issue by eddiejaoude** [guzzle/guzzle-services#86]
When using the `Mock Subscriber` with Guzzle Services, I always get an empty array?

Any ideas on this or examples / docs?

**Comment by gimler** [comment]
see also #70 
```
$client->getHttpClient()->getEmitter()->attach($history);
```

**Comment by GrahamCampbell** [comment]
Closing since stale - I'm doing a cleanup across the whole organization, to enable us to focus on the tickets that are still live and have interest. Please feel free to open a new issue if this still is important to you. :)
