### ISSUE TITLE
guzzle 6

### ISSUE THREAD

**Issue by gimler** [guzzle/guzzle-services#89]
Possible to upgrade to guzzle 6?

**Comment by bakura10** [comment]
Hi,

In addition to this, what is the status of the library? I have several libraries on guzzle 3 that I'd like to upgrade to this and guzzle 6 but as it's not v1 yet, I'm waiting.

As AWS no longer use guzzle services but a custom format, is it still the recommended way to create clients with Guzzle? Or do you think now it's actually better to follow what you're doing in AWS ?

**Comment by mtdowling** [comment]
I believe @jeremeamia has some plans for how move Guzzle service descriptions forward.

**Comment by gimler** [comment]
I rewrite my code actual from guzzle 3 to 5.3. The Missing feature is the responseClass feature see also #81.

**Comment by snoek09** [comment]
I'm having the same problem. I would like to know more about those plans @jeremeamia

**Comment by csarrazi** [comment]
:+1:

**Comment by csarrazi** [comment]
Would be glad to hear about these plans, too. I'd be glad to help. :)

**Comment by onema** [comment]
:+1:

**Comment by richhl** [comment]
same. I'm just deciding how to consume an api from my sf2 app. Have decide to use custom responseClass but i've just found it is a missing feature for guzzle-services 0.5. Thx

**Comment by hassankhan** [comment]
+1 any update on this?

**Comment by sonnygauran** [comment]
+1 on this too! 👍

**Comment by jpw123** [comment]
+1

**Comment by jeremeamia** [comment]
Hello everyone, I'm working on a Guzzle 6 version of `guzzle/command`, which is a dependency to this library. I should have a PR open sometime next week for review.

**Comment by csarrazi** [comment]
Great news, @jeremeamia! :)

**Comment by onema** [comment]
Awesome! :+1:

**Comment by mcrumm** [comment]
Sweeeeet! :+1:

**Comment by evancauwenberg** [comment]
Great! I'm looking forward to it!

**Comment by hassankhan** [comment]
Awesome news!! Thanks @jeremeamia!

**Comment by jpw123** [comment]
Thanks!! :+1:

**Comment by jimmypuckett** [comment]
@jeremeamia I am about to start a project that I would love to use service descriptions with guzzle 6, and I have been trying to decide what direction to go.  I just know that as soon as I get neck deep in going a different direction, you will release a great fix.

Do you have an ETA on this?

Thanks so much.

**Comment by jeremeamia** [comment]
Unfortunately I do not. Right now, I'm about half-way done with the `guzzle/command` package, but I haven't started doing anything specifically with this one yet. My family and I are also preparing to move across the country in too weeks, so I'm a little constrained on time. Sorry. I'll keep everyone posted mon my progress though.

**Comment by jimmypuckett** [comment]
@jeremeamia, thanks for letting me know.  I appreciate your effort & good luck with the move--moving sucks.

**Comment by jeremeamia** [comment]
I have a preview for [Guzzle 6 support in guzzle/command](https://github.com/guzzle/command/pull/30). Take a look and leave some feedback there, if you are interested.

**Comment by localheinz** [comment]
:+1:

**Comment by jeremeamia** [comment]
The `guzzlehttp/command` package is now updated for Guzzle 6 in [Version 0.9.0](https://github.com/guzzle/command/blob/master/CHANGELOG.md#090---2016-01-30). Now it's time to work on this one. :smile:

**Comment by onema** [comment]
This is great news @jeremeamia, thank you!

**Comment by hassankhan** [comment]
Awesome news!! Thanks @jeremeamia!

**Comment by bakura10** [comment]
You made my day. Thanks @jeremeamia . I will FINALLY by abe to rewrite all my Client in Guzzle 6 and remove this Guzzle 3 dependency :D.

**Comment by localheinz** [comment]
Nice job, @jeremeamia!

**Comment by hacfi** [comment]
@jeremeamia I started trying out the `guzzle6` branch and right now I always get `null` as the result. Looking into the execution I see that `GuzzleHttp\Promise\Promise::settle` gets called 7 times and after the correct response gets stored in `$this->result` it gets overwritten again to null. Any idea where this might come from? I’m more than happy to work on a PR to fix this but would need some guidance where this strange behaviour might come from. I assume the issue is not with the Promise library.

**Comment by hacfi** [comment]
Nevermind: https://github.com/guzzle/guzzle-services/blob/guzzle6/src/GuzzleClient.php#L48 is the source of the mysterious null response :)

**Comment by jeremeamia** [comment]
Yeah, this package is not quite Guzzle6 ready yet. Still working on it. The Command package has been updated already though.

**Comment by hacfi** [comment]
Yes, fully aware of that - really need this though so will try to make some progress and will create a PR if I make it work properly.

**Comment by dccampbell** [comment]
@jeremeamia Are there any specific G6 issues for others to take a look at right now, or are updates forthcoming? 

@hacfi Did you end up making any progress w/ that issue?

**Comment by csarrazi** [comment]
@jeremeamia Any help wanted for the guzzle6 branch stabilisation?

**Comment by jeremeamia** [comment]
Happy to have help. Haven't been able to work on this for a while, unfortunately. The current branch is in progress to update to use Guzzle 6 and the updated guzzlehttp/command and get the tests passing. Feel free to make PRs against that branch, and I'm happy to review.

**Comment by csarrazi** [comment]
Ok. Any specific things that still need a bit of work?

Or is the current work mostly focused on making the tests work with Guzzle6 and the `master` branch of guzzlehttp/command?

**Comment by jeremeamia** [comment]
> Or is the current work mostly focused on making the tests work with Guzzle6 and the master branch of guzzlehttp/command?

Yep, that. There are a few `@todo`s in there and some more find & replace work to do. It's been a few months since I looked at it, so I can't remember everything. I'd suggest just diving in and seeing what you can do with it. If you run into specific questions let me know, and I might be able to look at it and remember things.

**Comment by csarrazi** [comment]
Great, thanks for the pointers!
I'll take a look at this!

**Comment by jeremeamia** [comment]
Good luck, and thank you.

**Comment by snoek09** [comment]
@csarrazi What's the current status? Perhaps we can split this up and divide the todo's.

**Comment by csarrazi** [comment]
I've started migrating the Serializing part, for now. I'll try pushing something by the end of the week (as I'm currently abroad), but it won't be final.

**Comment by Konafets** [comment]
Any update on this?

**Comment by csarrazi** [comment]
Sorry, I was terribly busy lately. I will push some code tonight, once I get back home.

The current status is : nothing really usable for now, mostly working on serialization / deserialization, and trying to make the tests pass.

**Comment by csarrazi** [comment]
@Konafets @snoek09 You can find the code in the `guzzle6-pr1` branch of my fork.

https://github.com/csarrazi/guzzle-services/tree/guzzle6-pr1

**Comment by Konafets** [comment]
Thanks, I will try at the weekend. Thanks so far.

**Comment by WillBro** [comment]
Hello all,

Another keen observer here and I'm wondering if there has been an update since Jul 14th?

I've been investigating Guzzle 6 for a usecase at work and finally got to wrapping my head around the Guzzle3->6->psr-7 journey since I last looked.

@csarrazi Judging by your fork you (and open to all as well) have a good grasp of the library (promises and the handler stack in particular) how do we feel about the chance of guzzle-services and commands working together in an effort to use service descriptions?

**Comment by Konafets** [comment]
Hey, last two days a got familar with the code and have a pretty good overview what to do. I started already with fixing the request locations and some other issues. Mainly making the tests work again but also introduce new tests.

Comments are highly welcome.

https://github.com/Konafets/guzzle-services/tree/guzzle6-pr1

**Comment by Konafets** [comment]
Happy testing https://github.com/guzzle/guzzle-services/pull/109

**Comment by Konafets** [comment]
@jeremeamia Did you had the chance to have a look at my PR?

**Comment by Jaesin** [comment]
The guzzle 6 branch was created a couple of days ago so this can probably be closed: 

```bash
composer require guzzlehttp/guzzle-services:dev-guzzle6
```

**Comment by Konafets** [comment]
I will close this issue when the branch is merged and the release is tagged.

**Comment by Konafets** [comment]
Its finally done in 85c3969
