### ISSUE TITLE
Is it possible to NOT urlencode a specific uri parameter value?

### ISSUE THREAD

**Issue by fillup** [guzzle/guzzle-services#97]
I would like to be able to pass a value for a uri paramter and have it inserted into the url as is, but it is being automatically urlencoded right now. Is there a way to prevent that?

**Comment by mtdowling** [comment]
What's the use case? Have you already encoded the characters?

**Comment by fillup** [comment]
Thanks for the quick response @mtdowling. My use case is I'm working with an API that handles pagination of data by providing the query string to append to the API call that includes all the parameters and stuff. So in my definition I just have {pagination} as the parameter and I pass in the value I get back from the API. However when Guzzle makes the call it urlencodes the parameter so it doesn't work.

**Comment by Konafets** [comment]
@fillup Does your problem is still valid?

**Comment by blsn** [comment]
I'm having the same problem:
https://github.com/guzzle/guzzle/issues/1758

**Comment by Konafets** [comment]
Has nothing todo with this package.
