### ISSUE TITLE
Problems with postField params

### ISSUE THREAD

**Issue by michelt** [guzzle/guzzle-services#98]
Hey,

I'm using Guzzle 5.3 and guzzle-services 0.5. When I describe a service with POST method and postField params it generates a 400 bad request error (Error executing command: Client error response). It works well when I use "query" params instead.

Here is my code (description):

``` php
$description = new Description([
                'operations' => [
                    'createUser' => [
                        'httpMethod' => 'POST',
                        'uri' => 'users',
                        'responseModel' => 'jsonResponse',
                        'parameters' => [
                            'first_name' => [
                                'type' => 'string',
                                'location' => 'postField',
                                'required' => true
                            ],
                            'last_name' => [
                                'type' => 'string',
                                'location' => 'postField',
                                'required' => true
                            ],
                            'email' => [
                                'type' => 'string',
                                'location' => 'postField',
                                'required' => true
                            ],
                            'password' => [
                                'type' => 'string',
                                'location' => 'postField',
                                'required' => true
                            ]
                        ]
                    ]
                  ]
            ]);
```

And this is how I use that service:

``` php
$r = $client->createUser(array("first_name" => "toto", "last_name" => "titi", "email" => "tata", "password" => "tutu"));
```

As I said, it works when I change 'location' to 'query' instead of 'postField' (but I have to use post params).

Thanks for your help.

**Comment by jeremeamia** [comment]
Not sure why there would be an issue there. If you can capture debug or curl verbose output for each version (one using postField and one using query), that would help identify if there is an issue with this package or a misunderstanding of what the service actually needs.

**Comment by Konafets** [comment]
Is this issue still valid? Can you provide the requested debug output?

**Comment by Konafets** [comment]
Closed after no answer since four weeks. Feel free to reopen this issue.

**Note:** 1.0.0 of guzzle-services is out which is compatible with Guzzle6.
